/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vine.watcher

import kotlin.test.Test

class VMPClientTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = VMPClient()
    }
}
