service: vine-watcher

# You can pin your service to only deploy with a specific Serverless version
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: java11

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*Object"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "WineWatcherBucket" }, "/*" ] ] }
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::", { "Ref": "WineWatcherBucket" } ] ] }
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueAttributes"
        - "sqs:GetQueueUrl"
        - "sqs:ListQueues"
      Resource:
        Fn::GetAtt:
          - SlackCommandQueue
          - Arn

package:
  artifact: build/libs/vine-watcher-dev-all.jar

functions:
  vinewatcher-slack-poster:
    handler: vine.watcher.WinePosterLambda
    memorySize: 512
    timeout: 60
    events:
     - schedule: rate(1 hour)
    environment:
      SLACK_WEBHOOK: ${opt:slack-webhook}
      STAGE: ${opt:stage}

  vinewatcher-slack-webhook:
    handler: vine.watcher.slackhook.SlackCommandRequestHandler
    events:
      - http:
          path: event/receive
          method: post
          cors: true
    environment:
      SLACK_SIGNING_SECRET: ${opt:slack-signing-secret}
      QUEUE_URL:
        Ref: SlackCommandQueue

  vinewatcher-process-commands:
    handler: vine.watcher.queue.CommandProcessor
    memorySize: 512
    timeout: 20
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - SlackCommandQueue
              - Arn
    environment:
      SLACK_WEBHOOK: ${opt:slack-webhook}

resources:
  Resources:
    WineWatcherBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "vinewatcher-${opt:stage}"
    SlackCommandQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "SlackCommandQueue-${opt:stage}"

