/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package vine.watcher

import org.apache.http.client.entity.UrlEncodedFormEntity
import org.apache.http.client.methods.HttpGet
import org.apache.http.client.methods.HttpPost
import org.apache.http.client.utils.URIBuilder
import org.apache.http.impl.client.HttpClients
import org.apache.http.message.BasicNameValuePair

class App {

    private val httpclient = HttpClients.createDefault()

    fun csrfToken(): String {
        val httpGet = HttpGet("https://www.vinmonopolet.no")
        val response  = httpclient.execute(httpGet)
        response.use {
            return it.entity.content.bufferedReader().readLines()
                    .filter { it.contains("CSRFToken") }
                    .map { it.substringAfter("\"").substringBefore("\"") }
                    .first()
        }
    }

    fun availability(articleId: String, postalCode: String, csrfToken: String): String {
        val uri = URIBuilder("https://www.vinmonopolet.no/store-pickup/${articleId}/pointOfServices")

        val params = UrlEncodedFormEntity(listOf(
                BasicNameValuePair("CSRFToken", csrfToken),
                BasicNameValuePair("locationQuery", postalCode),
                BasicNameValuePair("entryNumber", "") // No entryNumber, no response!
        ))
        val httpPost = HttpPost(uri.build())
        httpPost.entity = params
        val response = httpclient.execute(httpPost)

        response.use {
            return it.entity.content.bufferedReader().readText()
        }
    }

}

fun main(args: Array<String>) {
    val app = App()
    val token = app.csrfToken()
    val availability = app.availability("8278501", "0484", token)
    println(availability)
}
